name: Generate Pac-Man Contribution Game

on:
  schedule:
    # runs every day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:    # allows manual runs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Generate Pac-Man contribution graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          username: alifiya2003
          output_path: output
          # Optional tweaks:
          # theme: dark
          # pacman_color: yellow
          # ghost_color: red

      - name: Commit generated graphs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/*.svg
          git commit -m "chore: update pacman graph" || echo "No changes to commit"
          git push
