name: 🐍 Generate & Deploy Contribution Snake

# Run daily at UTC midnight, or manually
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-snake:
    name: Build Snake Artifacts
    runs-on: ubuntu-latest
    outputs:
      dist-path: ${{ steps.set-path.outputs.dist-path }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Generate contribution-snake graphics
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake.gif?color_snake=yellow&color_dots=#ebedf0,#c6e48b,#7bc96f,#239a3b,#196127

      - name: Set dist path output
        id: set-path
        run: echo "::set-output name=dist-path::dist"

  deploy-pages:
    name: Deploy to GitHub Pages
    needs: build-snake
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ needs.build-snake.outputs.dist-path }}

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
